### ISSUE TITLE
Minecarts dont show up on bedrock clients

### ISSUE THREAD

**Issue by YasunaMC** [ProtocolSupport/ProtocolSupportPocketIssues#10]
![20180707_105234](https://user-images.githubusercontent.com/25864932/42409016-4167770e-81d4-11e8-947c-db3c662d2694.jpg)

![20180707_105227](https://user-images.githubusercontent.com/25864932/42409020-52728a52-81d4-11e8-80cb-8e43a5e4c161.jpg)

**Comment by magicus** [comment]
I am not able to reproduce this anymore in PE 1.7 on mcpenew. Minecrafts show up just fine, you can ride in them, and all look just great.

**Comment by magicus** [comment]
@YasunaMC If the problem still appears for you, please reopen.
