### ISSUE TITLE
Multiple firework issues

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#101]
There are multiple issues related to fireworks.
1) When flying using an elytra, using a firework results in no boost -- nothing happens.

~~2) When looking at a firework started by a PC player, the colors are off.~~

3) The actual firework rocket is invisible, you cannot see it flying off.

4) Crafting a firework star using gunpowder and colors does not work.

5) Crafting a firework rocket using a firework star, paper and gunpowder does not work.

~~6) If you try to pick up a firework rocket created with a firework star, PSPE crashes with an exception.~~

**Comment by magicus** [comment]
At least part of the fix is reviving this:
		//TODO FIX
		//registerToClient(Material.FIREWORK_CHARGE, pefireworks, ProtocolVersionsHelper.ALL_PE);
		//registerToClient(Material.FIREWORK, pefireworks, ProtocolVersionsHelper.ALL_PE);


However, a simple reactivation of the code did not do much good.

**Comment by magicus** [comment]
The crash is now fixed. It was due to bad NBT handling.

**Comment by magicus** [comment]
Remapping colors is now fixed.

**Comment by CtrlAltCuteness** [comment]
The issue with (1 - Fireworks Boosting with Elytra) is that while the Bedrock game can hold them in offhand, it is only to make Crossbows prioritize that ammo.

**Comment by magicus** [comment]
Elytra flying does not work even if rockets are in main hand.
