### ISSUE TITLE
Shield is missing

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#102]
With PE 1.10, the shield has finally come to Bedrock as well. But it does not work in PSPE, which knows nothing about this newfound ability of PE...

**Comment by CtrlAltCuteness** [comment]
Just a disclaimer for those who do not know: Java and Bedrock use different ways to "raise" the shield:

- **Java**: Just hold down the proper mouse button / key.
- **Bedrock** Just hold sneak (which is also fly down), which it then activates after a short pause and until you stop sneaking. (By default on Touch controls it is double-tapping the sneak button to actually toggle sneak.)
