### ISSUE TITLE
Enchantment tables no longer work [regression]

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketIssues#14]
In PE you click an enchantment table and POOF nothing happens

**Comment by magicus** [comment]
Still confirmed as of today in mcpenew. The "real" enchantment windows flashes on screen for a split second, and then disappears.

**Comment by magicus** [comment]
Just a small ping. This is still the case in the latest mcpenew.

**Comment by magicus** [comment]
Hopper enchantment restored. Only works in survival though. :(
