### ISSUE TITLE
Automatic light updates are not sent to PE players

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketIssues#15]
This issue is causing trees to have a darker shadow than usual

![Picture](https://user-images.githubusercontent.com/13177694/42358403-bd463782-80dc-11e8-8328-ab2e1b17f713.png)

**Comment by magicus** [comment]
affects_gameplay rationale: If you spawn inside a room, it can be completely dark, so it's impossible to play. (When it's just outside under some trees, it's more a visual_glitch).

**Comment by colinrgodsey** [comment]
fixed in https://github.com/ProtocolSupport/ProtocolSupport/pull/989

This was due to the StartGame position not being near the players real spawn position. the client would sometimes forgo lighting
