### ISSUE TITLE
Arrows does not fully work

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupportPocketIssues#18]
https://mrpowergamerbr.com/uploads/2018-05-29_15-29-34.gif

While arrow movement is kinda... wonky, it does work.

However it seems after an arrow hits an block, it just vanishes from the world.

**Comment by magicus** [comment]
There's something else with the arrows too. They seem to be delayed like one seconds. Makes it really hard to shoot a monster.

**Comment by magicus** [comment]
Ok, so arrows are not working correct, but the original description is not really right any longer either. The current status is this:
* Arrows fly basically the correct path, and they stay in the block afterwards.
* However, they fly too late, like the animation only starts until like the arrow has "actually" hit the target.
* The animation is also moving jerkily at times; the most common version of this is that you see the arrow real close, still, for like half a second before it starts moving away.
* Also, if the arrow hit a mob (monster or animal), the animation is not shown at all! It is only shown if the arrow hits a block.
* The firing sound however appears at the correct moment.
* Sometimes, I think the firing is lost. You pull back the bow, aim and release, and nothing happens. Unclear if this is some UI problem with Minecraft PE itself, or an issue with PSPE.

**Comment by magicus** [comment]
Ah, sorry, my bad. I did not test on correct server. :-(

**Comment by magicus** [comment]
It seems all the bullet points I listed above still applies. :-(

And also, in 1.8, the arrows are rotated 90 degrees when they hit a block.

In 1.7, arrows are incorrectly remapped to armor stands when they hit a block.

**Comment by caoli5288** [comment]
The movement issue is why entity motion not works.:-/

**Comment by colinrgodsey** [comment]
arrows work fully now 👍 @caoli5288 rotation fix, plus my extra rotation fixes, they're perfect now. tridents too
