### ISSUE TITLE
Enchanted items are missing purple glow

### ISSUE THREAD

**Issue by YasunaMC** [ProtocolSupport/ProtocolSupportPocketIssues#2]
no glow but if i add sharpnes wappon damage is it doese damage that intended

**Comment by YasunaMC** [comment]
@7kasper it's on tools weapons armor etc

**Comment by magicus** [comment]
@Artuto @YasunaMC Is this still a problem? I can't reproduce with latest version.

Also, I'd like to get a clarification: is the glowing purple missing from the item in the hot bar/inventory, or from the item when you hold it in your hand? Or both? (Both looked fine to me.)

**Comment by Artuto** [comment]
Just confirmed the glow is still missing

**Comment by magicus** [comment]
@Artuto Is it on the weapon in hand, or in the item in inventory?

**Comment by Artuto** [comment]
Both, also it affects to enchanted blocks and items too.

**Comment by YasunaMC** [comment]
@Artuto its only on yesdog branch but ... I didn't compile it yet
