### ISSUE TITLE
Serverbound packet freeze

### ISSUE THREAD

**Issue by WesleyVanNeck** [ProtocolSupport/ProtocolSupportPocketIssues#20]
without psps it just froze under heavy nbt remaping and some other shit
here is the log
[latest.log](https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/files/1957509/latest.log)

**Comment by magicus** [comment]
The current suggested workaround is to apply this patch to RakNetServer:
https://github.com/Shevchik/RakNetServer/pull/3

**Comment by colinrgodsey** [comment]
definitely fixed in the new raknet... closing this out as we now have a know fix

current PR: https://github.com/Shevchik/RakNetServer/pull/4

**Comment by magicus** [comment]
@colinrgodsey But this PR is still not merged in RakNey, yes? Until it is, I think we should keep this open as a tracking bug.

**Comment by 7kasper** [comment]
How's this right now? Has raknet been patched yet?

**Comment by WesleyVanNeck** [comment]
This is fixed so idk why it open still
