### ISSUE TITLE
Teleporting player to different yaw value doesn't work for pe clients

### ISSUE THREAD

**Issue by Speentie8081** [ProtocolSupport/ProtocolSupportPocketIssues#21]
Teleporting player to different yaw value doesn't work for pe clients.
This can be reproduced by having a player positioned with yaw 0 then trying to teleport them to the same location with yaw 90. The server recognizes that the direction the player is facing has been updated, but the client doesn't recognize that.
This is really messing up a mini-game on my server right now.
[https://youtu.be/IJTQvSVBAUU](url)

**Comment by magicus** [comment]
There is a chance that this might have been fixed by https://github.com/ProtocolSupport/ProtocolSupport/pull/997, which fixed yaw values for spawned objects. (If this code is involved in teleporting; I'm not sure about that).

@Speentie8081 Can you confirm if this is still happening?

**Comment by magicus** [comment]
I can confirm that /tp ~ ~ ~ 0 followed by /tp ~ ~ ~ 90 really rotates the player 90 degrees. At least after caolis fix. (Maybe was fixed before; don't know). Closing.

**Comment by magicus** [comment]
Ah, sorry, my bad. I did not test on correct server. :-(

**Comment by magicus** [comment]
Well, it does work for real for 1.8 on the correct server, so closing this. Properly, this time. :-)
