### ISSUE TITLE
Pistons do not show piston arm nor movement

### ISSUE THREAD

**Issue by 7kasper** [ProtocolSupport/ProtocolSupportPocketIssues#22]
They dont work yet.

**Comment by magicus** [comment]
While this might be "just" a visual glitch -- the pistons *do* work, mechanically, the lack of feedback makes it hard, almost impossible, to build anything but the simplest of redstone machines.

**Comment by 7kasper** [comment]
Piston arm is now fixed!
I got the collision to work for normal pistons too, but somehow collision ain't working for sticky pistons.
Weird, very weird indeed.

I don't think we can get (its not worth it because you'd need to make it simulated in PSPS) smooth extending as this is done clientside on PC.

**Comment by magicus** [comment]
This seem to work just fine in 1.9.
