### ISSUE TITLE
Players turn their body's instead of their heads in PE

### ISSUE THREAD

**Issue by 7kasper** [ProtocolSupport/ProtocolSupportPocketIssues#29]
When a player turns, it turns their body instead of their head and body.

**Comment by magicus** [comment]
I'm not exactly sure what the original bug meant, but as of today, there is at least one movement-related issue in PSPE (in mcpenew).

When a PE player looks around, this looks good for a PC client. First head moves a bit, then after a while the body follows.

But when a PC player looks around, this looks bad on a PE client. No changes at all is shown, the player is completely still, until a movement happens (in either direction), then suddenly the player is updated with the correct rotation.

**Comment by magicus** [comment]
Heh, what I described was actually #16. This one seem to be fixed.
