### ISSUE TITLE
Nether and End portals do not work

### ISSUE THREAD

**Issue by YasunaMC** [ProtocolSupport/ProtocolSupportPocketIssues#3]
same issue with end

**Comment by magicus** [comment]
I cannot reproduce this. I can teleport just fine to both Nether and the End.

@YasunaMC Can you give any specific instructions on how you failed to teleport? What version of PSPE did you use?

**Comment by magicus** [comment]
Ping @YasunaMC. Is this still happening? Can you provide more detail?
