### ISSUE TITLE
Missing particles when breaking blocks myself (not others)

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#30]
When breaking blocks, the blocks disappear without an animation on PE.

This is on an iPad. Reproduced at mcpeinventory#de1cfdda28de4db41e4581f2e245cff6285c79e1

**Comment by magicus** [comment]
Confirmed still present in mcpenew as of today, on PE 1.7. (mcpelinux/Android)

When PC player is breaking block, animation shows on both PC and PE. When PE player is breaking block, animation is only showing on PC, not PE.

**Comment by YasunaMC** [comment]
@magicus  it works for me fine i can see that

**Comment by YasunaMC** [comment]
@magicus am using android

**Comment by YasunaMC** [comment]
Wine 10 works also

**Comment by magicus** [comment]
This is really odd. Apparently it works in some cases, and not in others. Fortunately, it's just a visual glitch so we might just have to keep this on the radar.

**Comment by magicus** [comment]
Funnily enough, I actually saw a single breaking animation happen today. So maybe it's some kind of race/packet ordering issue..?

**Comment by magicus** [comment]
I've tracked down the "intermittent" case for me, anyway. It was not intermittent. What happened was that if you break a block with eg a button on it, you will see the particles for the button (but not the block you are destroying). If you destroy the button directly, you will see nothing.

**Comment by magicus** [comment]
I am *still* seeing this. I realize now that I read the backlog that I maybe have not been fully clear about the issue; I talked about "animation" but now I know the proper word is "particles". When you break a block, you are supposed to see a cloud of particles coloured as part of the block you are breaking.

You see these particles on PE, but only when other people are breaking blocks, not when you do it yourself. Still present in 1.9 and latest PSPE.
