### ISSUE TITLE
Rabbits are too big

### ISSUE THREAD

**Issue by InsaneLegacy** [ProtocolSupport/ProtocolSupportPocketIssues#32]
Just spawn a rabbit in pe you will see what I mean

**Comment by 7kasper** [comment]
Needs proper metadata remap. Maybe we need to set an optional initial size inside the entitydata.json file..

**Comment by magicus** [comment]
I can confirm this in mcpenew today.

**Comment by magicus** [comment]
This also affects other entities, such as baby zombies.

**Comment by colinrgodsey** [comment]
baby rabbits seem fine... just the adults. super odd

**Comment by TacoGuyAT** [comment]
baby zombies are just default zombies but with bigger head, same issue, ig
