### ISSUE TITLE
Spawn egg items are incorrectly mapped

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#33]
Spawn eggs items are incorrectly mapped. They show up as "generic" white (!) spawn eggs when e.g. stored in a chest, and they all just spawn pigs.

**Comment by magicus** [comment]
Argh, it's just all messed up. :-( For instance, we currently have zombie spawn eggs as pedata 54, but that will spawn a horse. And spiders have pedata 52, but that will spawn a vex.

I have looked around the web for a proper list of spawn egg ids on PE (the IDs we have are from java edition, and they clearly do not match up), but found nothing. Back to the good ol´ trial and terror, I believe..

**Comment by 7kasper** [comment]
You fixed it (i think) 😄

**Comment by colinrgodsey** [comment]
1.8 broke this again. Eggs dont have the legacy durability anymore, they have an NBT tag with the entity name.

**Comment by magicus** [comment]
Also, all spawn eggs are black. But maybe that is just a result of the change to NBT tags..?

**Comment by magicus** [comment]
Actually, spawn eggs work just fine in 1.9. But they look black. I'll open a separate bug for that.
