### ISSUE TITLE
Shulker boxes are upside down

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#34]
**Describe the bug**
Shulker boxes appear upside down, however they're correctly placed in PC. 

**How can we reproduce the issue?**
1. Put a shulker box in PC
2. Join with MCPE
3. See the issue

**Expected behavior**
The shulker box should be kept in the same position.

**Comment by magicus** [comment]
Confirmed.

**Comment by 7kasper** [comment]
Fixed!

**Comment by Artuto** [comment]
Occurs again in latest mcpenew PE 1.10

![](https://cdn.discordapp.com/attachments/497480149059633152/558427797274492958/Screenshot_2019-03-21-17-11-37.png)

Please reopen @magicus @7kasper

**Comment by magicus** [comment]
Confirmed again on 1.9 and 1.10. However, placing the shulker box directly looks fine. But when logging out and back in, it has turned upside down.

**Comment by magicus** [comment]
Fixed. Was the broken tile entity cache.
