### ISSUE TITLE
Villager trading GUI does not work

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#35]
**Describe the bug**
While taping on a villager to open its gui the server kicks you with an error message or it just doesn't open anything

**How can we reproduce the issue?**
1. Have a villager
2. Tap on it to open its trading GUI

**Expected behavior**
The gui should open.

**Comment by 7kasper** [comment]
You cannot trade with nidwids. I cannot reproduce the opening issue, but I fixed the crash on trade 🎊

**Comment by 7kasper** [comment]
Please open another issue if you still have problems opening trade with villagers that you can trade with on pc.
