### ISSUE TITLE
Incorrect remap of powered redstone lamps

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#37]
Powered redstone lamps are mapped incorrectly, they appear as air.

**Comment by YasunaMC** [comment]
yes this is anoying @magicus plz if you have time fix this because i cant find were remaps are

**Comment by magicus** [comment]
This is fixed with https://github.com/ProtocolSupport/ProtocolSupport/pull/971
