### ISSUE TITLE
Pressure plates are remapped incorrectly

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#42]
Pressure plates appear as air

**Comment by magicus** [comment]
That's bad. Is it the new "special wooden" pressure plates, e.g. spruce pressure plate? Or is it plain old oak and stone pressure plates?

**Comment by Artuto** [comment]
@magicus Apparently oak pressure plates. Didn't test with another types

**Comment by magicus** [comment]
I have a fix pending for oak pressure plates. I think other wooden types are broken as well, but that depends on a bug in the remapping system rather than the type values themselves.

**Comment by 7kasper** [comment]
![image](https://user-images.githubusercontent.com/6474340/49676123-c43aaf80-fa78-11e8-921a-3297238ebbda.png)
