### ISSUE TITLE
Remove bad item remaps

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#43]
Now that the itemmapping.json is (more or less) correct, and PE 1.7 supports (more or less) the same items/blocks as 1.13 does, we should remove some old and incorrect remapping that is taking place.

The following items are remapped incorrectly:
* ~~All prismarine (normal, dark, brick) stairs remap to cobblestone. (This is the same with blocks, probably the source of the error)~~
* ~~Carved pumpkin remap to (plain) pumpkin.~~
* Banners of all colours remap to white banners.
* Beds of all colours remap to red beds.

There are possibly more that I've missed.

I do not understand where this remapping is happening. A prime suspect would be the remapping in LegacyBlockData, but that should only affect blocks, not items, as far as I understand.

**Comment by YasunaMC** [comment]
@magicus  you forgot some slabs still some stone slabs are air

**Comment by magicus** [comment]
@YasunaMC I'm talking about items here, not block. If item mapping is correct then you can exchange items with PC players, e.g. by putting them in a chest with one player, and removing it from the chest by the other, and both players see the same item. As far as I know, this works correctly for stone slabs. Does this fail for you?

If you try to use the item to create a block, and this does not give the correct block, then the issue is with block mapping. (Which is known to be still incorrect).

**Comment by magicus** [comment]
Also a very weird thing is wooden buttons get kind of "rotated" in the intentory item display box. Looks really odd.

**Comment by magicus** [comment]
Fixed, except beds and banners which are separate bugs.
