### ISSUE TITLE
[PSB] Game mode mode not updated when changing servers

### ISSUE THREAD

**Issue by colinrgodsey** [ProtocolSupport/ProtocolSupportPocketIssues#46]
Should be an easy fix, just putting it here so i dont forget.

**Comment by magicus** [comment]
@colinrgodsey Might this be related to #41?

**Comment by colinrgodsey** [comment]
Should be fixed now in https://github.com/ProtocolSupport/ProtocolSupportBungee/pull/69

https://github.com/ProtocolSupport/ProtocolSupportBungee/pull/69/commits/7d6e0dcaf0f730a34172f7e7afc8151e871b6153

**Comment by colinrgodsey** [comment]
fixed in new bungee
