### ISSUE TITLE
Double stone slabs aren't remapped correctly

### ISSUE THREAD

**Issue by MrPowerGamerBR** [ProtocolSupport/ProtocolSupportPocketIssues#49]
**PE:**
![https://cdn.discordapp.com/attachments/286106780189065216/520958545924063239/Screenshot_20181208-114307.png](https://cdn.discordapp.com/attachments/286106780189065216/520958545924063239/Screenshot_20181208-114307.png)

**PC:**
![https://cdn.discordapp.com/attachments/286106780189065216/520958610054971392/unknown.png](https://cdn.discordapp.com/attachments/286106780189065216/520958610054971392/unknown.png)

**Comment by magicus** [comment]
Will be fixed by https://github.com/ProtocolSupport/ProtocolSupport/pull/977.

**Comment by MrPowerGamerBR** [comment]
Fixed by @magicus :clap:
