### ISSUE TITLE
Villager trading still not working properly

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#50]
When starting a villager trade, your own inventory gets messed up. The three first items in the hotbar gets copied from the three last. The items previously in the three last appears in your inventory, and the three in the middle from the hotbar is duplicated there, and items already in the inventory gets duplicated.

Opening inventory with E still shows this messed up version, but opening a chest will restore it to normal.

This is after @7kasper fix today for villager trading.

**Comment by magicus** [comment]
... and when that happens (opening a chest), all you traded are lost.

**Comment by 7kasper** [comment]
I had this too, but only for a brief moment until the next inventory update came in. I will look into it, but I have tested trading of multiple items. Weird 😕

**Comment by magicus** [comment]
For a while, this seemed to work for me in 1.7. But now, in 1.8, trading does not even open a GUI. :-(

**Comment by Artuto** [comment]
Was fixed too
