### ISSUE TITLE
Some particles don't show up

### ISSUE THREAD

**Issue by EmiliaYT** [ProtocolSupport/ProtocolSupportPocketIssues#56]
like splash particles
1. Join with PE '1.8 and 1.7'
2. Do ' frow a splash potions or XP botlle'
3. there you have it i will add video  soon

**Comment by YasunaMC** [comment]
https://youtu.be/wEswUyq9l8k

**Comment by magicus** [comment]
Overall, I believe particles are missing in many occasions. This has been an under-prioritized area.

**Comment by colinrgodsey** [comment]
all server-driven particles should work now. throwing splash potions is a bit odd still.... but once the effects are on the entity, you can see em now 👍
