### ISSUE TITLE
Leaves are completely dark

### ISSUE THREAD

**Issue by Artuto** [ProtocolSupport/ProtocolSupportPocketIssues#58]
In latest mcpenew all the leaves are shown completely black, even with a direct source of light right away.

**Comment by colinrgodsey** [comment]
can you confirm with my new branch, see if this is still an issue? (fixed some stuff that went weird with the merge to mcpenew). might also want to try my new bungee with it- cleans up the initialization phases a bit more

**Comment by Artuto** [comment]
Fixed
