### ISSUE TITLE
Random client crashes

### ISSUE THREAD

**Issue by YasunaMC** [ProtocolSupport/ProtocolSupportPocketIssues#6]
If you guys wanth a logcat from when that happens I can provide it when am home

**Comment by magicus** [comment]
@YasunaMC This bug was reported July 20. Is this still a problem? Much has changed in that time. If this is not happening anymore, please close.

Otherwise, I might close it anyway :-) and ask you to open a new bug if you still experience crashes.

**Comment by YasunaMC** [comment]
Its isn't a problem any more
