### ISSUE TITLE
Texture glitches on neigbour blocks when interacting with blocks

### ISSUE THREAD

**Issue by samolego** [ProtocolSupport/ProtocolSupportPocketIssues#62]
**Describe the bug**
Describe the bug as clearly as you can.

(Bedrock edition, Android)
Clicking a block with GUI will make one of the neighbour blocks get the same texture as the block you're interacting with. It goes away after closing the GUI. It's **not** so important bug, just strange behaviour.

**How can we reproduce the issue?**
1. Make sure to have "desktop" GUI enabled, not the pocket one.
2. (optional) Apply a resource pack with semi-transparent GUI (so you can see through)
3. Click any interactable block like crafting table, furnace, anvil etc.

**Expected behavior**

Other blocks should stay as they are.

**Screenshots**
If applicable, please attach screenshots of both the Java and Bedrock edition of the game. 

http://imgur.com/gallery/wN9Q7Ac
http://imgur.com/gallery/FcRnIzv

**What version of ... are you using?**
Tell us the commit and the branch of ProtocolSupport are you using (also include /ps buildinfo),
also include the Client version (EX: Android - PE 1.7.0.13).

client: Android, PE 1.9.0.15
server: ProtocolSupport (mcpenew branch) - buildtime: 2019.02.27 at 20:14:00 CET, buildhost: jenkins.krusic22.com, buildnumber: origin/mcpenew / 9ddacd1ed399b0ff4c6368cb0406c959b8103c0e)

**Comment by Shevchik** [comment]
Blame mojang for implementing GUI retarded way.
Fake block is needed for gui to work.

**Comment by samolego** [comment]
Ok, didn't know that. Sorry.

**Comment by 7kasper** [comment]
No need to apologise, it is indeed something we won't fix. It's not a bug its a feature 😄

**Comment by samolego** [comment]
Nice one :-P. Keep up good work!
