### ISSUE TITLE
All mob head blocks look like skeleton skulls

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#73]
All mob heads appear as skeleton heads as items (in a chest or the inventory) on PE.

All mob heads are missing proper block remaps, so when placed as a block, nothing is shown.

**Comment by magicus** [comment]
This is partially fixed. Mob head items work properly, and it is possible to see mob heads. However, all mob heads show up as skeleton skulls.

**Comment by magicus** [comment]
This will be fixed with https://github.com/ProtocolSupport/ProtocolSupport/pull/1063.

**Comment by OnlyBMan** [comment]
This can now be closed! 😄
