### ISSUE TITLE
Intermittent client crash when entering Nether

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#77]
The PE client crashes sometimes (roughly 50% of the times) when the player enters the Nether (or goes back to the Overworld). A subsequent login works fine, and you have then appeared at your wanted destination, so this is not a complete show-stopper, but it is quite an annoyance.

**Comment by WesleyVanNeck** [comment]
Finaly some ons see this i reported it on discord

**Comment by magicus** [comment]
Actually, I've had this problem in my old (but surprisingly stable!) build of PSPE from February last year, supporting PE 1.7 and Java 1.12. So maybe it's a super-old issue, and maybe it's something completely new, considering how much effort has gone into rewriting the dimension switch code.

**Comment by magicus** [comment]
This should be fixed with Yesdogs latest patch.
