### ISSUE TITLE
Wrong block remaps

### ISSUE THREAD

**Issue by YasunaMC** [ProtocolSupport/ProtocolSupportPocketIssues#8]
no errors or abnormal log

**Comment by magicus** [comment]
I think most blocks are mapped correctly now. There are still some isses. Fern, for instance, looks like grass. Shulker boxes are rendered upside down (!). 

We should really need a good testing map which displays all available blocks. There must surely be such a thing to be found out there..? I've been using ExMaple (demo map for MC map generators), which is quite good but does not cover all blocks, and they are spread out over a large area, making verification impractical.

**Comment by 7kasper** [comment]
I will close this issue. Since almost all remaps are fixed thanks to @magicus, please open individual issues per wrong block like #34 . Thanks!
