### ISSUE TITLE
Can't interact with Citizens or Shopkeepers NPCs

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#92]
Can't interact with Citizens or Shopkeepers NPCs.

This is from https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/61, as reported by @Artuto. 

I have not verified this, but assume this is basically the same issue as villager trading not working.

**Comment by Artuto** [comment]
Just tested and this is fixed. You can close
