### ISSUE TITLE
Riding an entity moves you under the ground (using CMI's stairs as chairs)

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketIssues#93]
Riding an entity moves you under the ground (using CMI's stairs as chairs).

This is from #61, as reported by @Artuto.

I have not verified this.

**Comment by colinrgodsey** [comment]
this should just be the 'rider offset' on armor stands (assuming its using armor stands to make you sit)

**Comment by magicus** [comment]
I have verified that minecarts and boats look fine, so it's likely this is something to do with armor stands, yes.
