### ISSUE TITLE
BE clients dont see swimming animations

### ISSUE THREAD

**Issue by BNTFryingPan** [ProtocolSupport/ProtocolSupportPocketIssues#98]
**Describe the bug**
Bedrock Edition clients cannot see swimming animations for anyone (incuding self)

**How can we reproduce the issue?**
1. Have 1 BE client, and 1 Java client in the water
2. Swim around with either client
3. Notice that the Java client will see the swimming animations of both players, but the BE client sees neither swimming animation

**Expected behavior**
The BE client sees swimming animations

**Screenshots**
Very difficult to get screenshots of this

**What version of ... are you using?**
Minecraft Java 1.13.2 (server and client)
Server: Paper 1.13.2 build 568
Minecraft Windows 10 Edition v1.10.0

**Additional information**
![image](https://user-images.githubusercontent.com/7706960/54891136-bae81e00-4e82-11e9-8bbd-6c8b19f9a588.png)

**Comment by WesleyVanNeck** [comment]
Pe self doesnt swim it hopping in the water before aqautic update

**Comment by magicus** [comment]
Fixed.
